# Generated by Django 6.0.6 on 2026-06-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('goods', 'Goods'), ('service', 'Service')], max_length=10)),
                ('hsn_code', models.CharField(blank=True, max_length=6, null=True)),
                ('sac_code', models.CharField(blank=True, max_length=6, null=True)),
                ('tax_type', models.CharField(choices=[('taxable', 'Taxable'), ('non_taxable', 'Non-Taxable')], max_length=15)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
